openapi: 3.0.0
info:
    title: Jobs API
    description: API for managing jobs and user authentication
    version: 1.0.0

servers: [url: https://jobsapi-0k8q.onrender.com/api/v1]

paths:
    /auth/register:
        post:
            tags:
                - auth
            summary: Register a new user
            description: Register a new user to the system
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                                email:
                                    type: string
                                    format: email
                                password:
                                    type: string
            responses:
                '200':
                    description: User registered successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    token:
                                        type: string

    /auth/login:
        post:
            tags:
                - auth
            summary: Login a user
            description: Login to get an authentication token
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    format: email
                                password:
                                    type: string
            responses:
                '200':
                    description: Login successful
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    token:
                                        type: string

    /jobs:
        get:
            tags:
                - jobs
            summary: Get all jobs
            description: Retrieve a list of all jobs
            security:
                - bearerAuth: []
            responses:
                '200':
                    description: List of jobs

        post:
            tags:
                - jobs
            summary: Create a new job
            description: Create a new job listing
            security:
                - bearerAuth: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                company:
                                    type: string
                                position:
                                    type: string
                                status:
                                    type: string
            responses:
                '201':
                    description: Job successfully created
                '400':
                    description: Bad request

    /jobs/{id}:
        get:
            tags:
                - jobs
            summary: Get a job by ID
            description: Retrieve a specific job by its ID
            security:
                - bearerAuth: []
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: Job details
                '404':
                    description: Not found

        patch:
            tags:
                - jobs
            summary: Update a job by ID
            description: Update a specific job by its ID
            security:
                - bearerAuth: []
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                position:
                                    type: string
                                company:
                                    type: string
            responses:
                '200':
                    description: Job updated successfully
                '400':
                    description: Bad request

        delete:
            tags:
                - jobs
            summary: Delete a job by ID
            description: Delete a specific job by its ID
            security:
                - bearerAuth: []
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: Job deleted successfully

components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
